name: Deploy UI to Cloud Run

on:
  push:
    branches:
      - main

    #
    # Run only when book-ui/ changes or cd workflow file changes
    #
    paths:
      - 'booky_ui/**'                     
      - '.github/workflows/ui-cd.yml'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    #
    # Required permissions for Workload Identity Federation
    #
    permissions:
      contents: read
      id-token: write

    steps:
      #
      # 1. Checkout repository code
      #
      - name: Checkout Code
        uses: actions/checkout@v4

      # Debugging
      - name: Print GitHub OIDC Claims
        run: |
          echo "Repository:      '${{ github.repository }}'"
          echo "Repository Owner:'${{ github.repository_owner }}'"
          echo "Ref/Branch:      '${{ github.ref }}'"
          echo "Environment:     '${{ job.environment }}'"

      #
      # 2. Authenticate to GCP using Workload Identity Federation
      #
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      #
      # 3. Deploy source code directly to Cloud Run
      #
      - name: Deploy UI Service
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: booky-ui-dev
          region: us-east5              
          source: ./booky_ui               
          flags: '--allow-unauthenticated' # Public access